require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShowdownsController do

  # This should return the minimal set of attributes required to create a valid
  # Showdown. As you add validations to Showdown, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ShowdownsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all showdowns as @showdowns" do
      showdown = Showdown.create! valid_attributes
      get :index, {}, valid_session
      assigns(:showdowns).should eq([showdown])
    end
  end

  describe "GET show" do
    it "assigns the requested showdown as @showdown" do
      showdown = Showdown.create! valid_attributes
      get :show, {:id => showdown.to_param}, valid_session
      assigns(:showdown).should eq(showdown)
    end
  end

  describe "GET new" do
    it "assigns a new showdown as @showdown" do
      get :new, {}, valid_session
      assigns(:showdown).should be_a_new(Showdown)
    end
  end

  describe "GET edit" do
    it "assigns the requested showdown as @showdown" do
      showdown = Showdown.create! valid_attributes
      get :edit, {:id => showdown.to_param}, valid_session
      assigns(:showdown).should eq(showdown)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Showdown" do
        expect {
          post :create, {:showdown => valid_attributes}, valid_session
        }.to change(Showdown, :count).by(1)
      end

      it "assigns a newly created showdown as @showdown" do
        post :create, {:showdown => valid_attributes}, valid_session
        assigns(:showdown).should be_a(Showdown)
        assigns(:showdown).should be_persisted
      end

      it "redirects to the created showdown" do
        post :create, {:showdown => valid_attributes}, valid_session
        response.should redirect_to(Showdown.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved showdown as @showdown" do
        # Trigger the behavior that occurs when invalid params are submitted
        Showdown.any_instance.stub(:save).and_return(false)
        post :create, {:showdown => { "name" => "invalid value" }}, valid_session
        assigns(:showdown).should be_a_new(Showdown)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Showdown.any_instance.stub(:save).and_return(false)
        post :create, {:showdown => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested showdown" do
        showdown = Showdown.create! valid_attributes
        # Assuming there are no other showdowns in the database, this
        # specifies that the Showdown created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Showdown.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => showdown.to_param, :showdown => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested showdown as @showdown" do
        showdown = Showdown.create! valid_attributes
        put :update, {:id => showdown.to_param, :showdown => valid_attributes}, valid_session
        assigns(:showdown).should eq(showdown)
      end

      it "redirects to the showdown" do
        showdown = Showdown.create! valid_attributes
        put :update, {:id => showdown.to_param, :showdown => valid_attributes}, valid_session
        response.should redirect_to(showdown)
      end
    end

    describe "with invalid params" do
      it "assigns the showdown as @showdown" do
        showdown = Showdown.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Showdown.any_instance.stub(:save).and_return(false)
        put :update, {:id => showdown.to_param, :showdown => { "name" => "invalid value" }}, valid_session
        assigns(:showdown).should eq(showdown)
      end

      it "re-renders the 'edit' template" do
        showdown = Showdown.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Showdown.any_instance.stub(:save).and_return(false)
        put :update, {:id => showdown.to_param, :showdown => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested showdown" do
      showdown = Showdown.create! valid_attributes
      expect {
        delete :destroy, {:id => showdown.to_param}, valid_session
      }.to change(Showdown, :count).by(-1)
    end

    it "redirects to the showdowns list" do
      showdown = Showdown.create! valid_attributes
      delete :destroy, {:id => showdown.to_param}, valid_session
      response.should redirect_to(showdowns_url)
    end
  end

end
